class 구현
711skhu/mobile pull request #1
Opened 2019-04-16 08:51 UTC by kje6445

2019-04-16 11:19 UTC, shouwn requested changes

2019-04-16 11:19 UTC, shouwn commented on src/main/java/com/shouwn/oj/controller/BuildingInquiryController.java
> +package com.shouwn.oj.controller;
패키지는 다른 프로젝트와 동일하게
controller - {domain name} 형식으로 해주세요.

2019-04-16 11:19 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/enums/DetailType.java
> +package com.shouwn.oj.model.enums;
enums 도 다른 것과 마찬가지로 
enums - {doman name} 형식으로 적어주세요.

2019-04-16 11:19 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/enums/DetailType.java
> +@Getter
enum에 현재 getter를 만들 필드가 없기 때문에 getter는 제외해도 좋을 것 같네요.

2019-04-16 11:19 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/enums/RentDate.java
> +@MappedSuperclass
MappedSuperclass가 어떤 것인지 알고 계신가요?

2019-04-16 11:19 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/enums/RentDate.java
> +    LocalDate rentDay;
필드는 모두 private로 만들어 주세요.

2019-04-16 11:19 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/lectureRoom/LectureRentState.java
> +public class LectureRentState {
여기에는 @Getter 어노테이션이 붙어 있지 않네요. 다른 곳에서 get을 못 할 것 같아요.
마찬가지로 생성자 또는 setter가 없기 때문에 set 도 못 할 것 같네요

2019-04-16 11:19 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/lectureRoom/LectureRoom.java
> +public class LectureRoom extends Building {
Building 클래스와 컴포넌트 관계가 아니라 자식 클래스로 만든 이유가 무엇인가요?

2019-04-16 11:19 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/enums/RentDate.java
> +package com.shouwn.oj.model.enums;
RentDate는 enums가 아니라 모델에 있는 게 맞는 것 같아요

2019-04-16 11:19 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/user/User.java
> +public class User {
여기도 마찬가지로 getter와 setter 혹은 생성자가 없네요

2019-04-16 11:19 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/request/RentRequest.java
> +    private  int endTime;
여기서는 startTime 과 endTime을 만들고 LectureRoom에서는 RentDate로 만든 이유가 있나요?

2019-04-16 11:19 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/request/RentRequest.java
> +public class RentRequest extends User {
User클래스를 상속한 이유가 무엇인가요?

2019-04-16 11:19 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/request/RentRequest.java
> +package com.shouwn.oj.model.request;
request 도 다른 것과 마찬가지로
request - {domain name} 형식으로 패키지를 작성해주세요

2019-04-16 12:33 UTC, KimJye submitted a review, later dismissed

2019-04-16 12:43 UTC, lwiiiiii commented on src/main/java/com/shouwn/oj/model/user/User.java
> +public class User {
core 프로젝트와는 다른 DB를 사용하는 건가용??

2019-04-16 12:43 UTC, yjll1019 commented on src/main/java/com/shouwn/oj/model/enums/RentDate.java
> +public class RentDate {
이 클래스는 빌리는 기간을 나타내는 클래스인가욥?
start와 end는 시간을 의미하는건가요???

2019-04-16 12:45 UTC, KimJye commented on src/main/java/com/shouwn/oj/controller/BuildingInquiryController.java
> +
컨트롤러 어노테이션은..나중에 추가할 예정이신가요??

2019-04-17 01:47 UTC, kje6445 commented on src/main/java/com/shouwn/oj/model/user/User.java
> +public class User {
넵! mobile 서버는 따로 DB가 필요없다고 느껴져셔 만들지 않았고 강의실 세부 사항을 정리하는데 필요한 정보는 enum의 Detail에서 정의해서 받기로 했습니다.

2019-04-17 01:57 UTC, kje6445 commented on src/main/java/com/shouwn/oj/controller/BuildingInquiryController.java
> +package com.shouwn.oj.controller;
네! 수정해서 다시 올리겠습니다.

2019-04-17 01:57 UTC, kje6445 commented on src/main/java/com/shouwn/oj/model/enums/DetailType.java
> +package com.shouwn.oj.model.enums;
네! 수정해서 다시 올리겠습니다.

2019-04-17 01:58 UTC, kje6445 commented on src/main/java/com/shouwn/oj/model/enums/DetailType.java
> +@Getter
네! 수정해서 다시 올리겠습니다.

2019-04-17 01:59 UTC, kje6445 commented on src/main/java/com/shouwn/oj/model/enums/RentDate.java
> +@MappedSuperclass
네! 수정해서 다시 올리겠습니다.

2019-04-17 01:59 UTC, kje6445 commented on src/main/java/com/shouwn/oj/model/enums/RentDate.java
> +    LocalDate rentDay;
네! 수정해서 다시 올리겠습니다.

2019-04-17 02:07 UTC, kje6445 commented on src/main/java/com/shouwn/oj/model/enums/RentDate.java
> +public class RentDate {
네! 그런 의미로 쓰였습니다. RentDate의 rentDay에 선택된 날짜를 받고 언제부터 언제까지 빌릴 것인지 start와 end로 정했습니다. 헷갈리는 부분이 있어 startTime, endTime으로 수정했습니다.

2019-04-17 02:09 UTC, kje6445 commented on src/main/java/com/shouwn/oj/controller/BuildingInquiryController.java
> +
일단 제대로 하고 있는지 알고 싶어서 올렸구 주말전까지 추가해서 다시 업로드 할 예정입니다.

2019-04-17 06:42 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/user/User.java
> +public class User {
다시 말씀을 드리면 mobile 도 core의 DB를 사용합니다.

mobile 에서는 학사 정보 시스템에 로그인 할 필요가 있기 때문에 core의 Member 클래스로 얻는 정보 외에 사용자로부터 얻은 학사 정보 시스템의 학번과 비밀번호가 필요하기 때문에 User 클래스가 있습니다.

2019-04-17 06:44 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/enums/RentDate.java
> +public class RentDate {
추가로 말씀드리겠습니다.

대여가 분 단위가 안 되고 시 단위만 되기 때문에 시 부분만 있으면 될 것이라 생각하여 현재 startTime endTime이 int 형 입니다.

2019-04-18 17:15 UTC, kje6445 commented on src/main/java/com/shouwn/oj/model/user/User.java
> +public class User {
추가했습니다.

2019-04-18 17:21 UTC, kje6445 commented on src/main/java/com/shouwn/oj/model/request/RentRequest.java
> +    private  int endTime;
강의실을 클릭했을 때 그 강의실의 각 빌렸던 시간별 항목들이 리스트처럼 보여줘야한다고 생각해서 그렇게 하였습니다.

2019-04-18 17:25 UTC, kje6445 commented on src/main/java/com/shouwn/oj/model/request/RentRequest.java
> +public class RentRequest extends User {
내가 빌렸던 강의실 목록을 확인할 때 내가 누군지 알아야 내가 빌렸던 항목을 불러올 수 있을 것 같다는 생각에서 그렇게 했어요!

2019-04-18 17:27 UTC, kje6445 commented on src/main/java/com/shouwn/oj/model/enums/RentDate.java
> +package com.shouwn.oj.model.enums;
enums에 있는게 맞다고 생각했었는데 모델로 바꾸는게 더 좋은 이유가 어떤거에요?

2019-04-20 00:53 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/request/RentRequest.java
> +    private  int endTime;
response를 위한 모델인가요?

2019-04-20 00:55 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/request/RentRequest.java
> +public class RentRequest extends User {
누군지 알아야 하는 건 맞지만 상속하고는 맞지 않는 것 같습니다.
컴포넌트 관계를 가지는 건 어떤가요?

2019-04-20 00:56 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/enums/RentDate.java
> +package com.shouwn.oj.model.enums;
RentDate가 클래스이기 때문입니다. enums는 enums 들만 모아놓은 곳이기 때문이죠

2019-04-20 08:31 UTC, songz1 requested changes

2019-04-20 08:31 UTC, songz1 commented on src/main/java/com/shouwn/oj/controller/building/BuildingInquiryController.java
> +}
강의실별 대여현황 확인도 BuildingInquiryController에서 이루어지나요? 
추가로, 나의 대여 내역을 조회하는 컨트롤러도 필요할 것 같아요.

2019-04-20 08:31 UTC, songz1 commented on src/main/java/com/shouwn/oj/model/enums/rent/RentStateType.java
> +    APPOROVAL,
APPROVAL 오타인 듯 해요!

2019-04-20 08:31 UTC, songz1 commented on src/main/java/com/shouwn/oj/model/rent/RentRequest.java
> +    private int number; //대여 인원
대여 신청할 때 대여 인원이 아니라 대여 인원 목록을 보내야해요! String으로 변경해주세요.

2019-04-20 08:31 UTC, songz1 commented on src/main/java/com/shouwn/oj/model/lectureRoom/LectureRoom.java
> +    RentDate rentDate;
DetailType과 RentDate는 LectureRentState 클래스로 받아오기 때문에 여기선 강의실 정보만 담고있으면 될 것 같아요.

2019-04-20 08:31 UTC, songz1 commented on src/main/java/com/shouwn/oj/model/rent/RentRequest.java
> +public class RentRequest extends User {
User를 왜 상속하는건가요?

2019-04-21 06:21 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/response/rent/RentDate.java
> +}
Setter 어노테이션이나 생성자가 없기 때문에 객체에 데이터를 넣는 것이 불가능할 것 같습니다.

2019-04-21 06:23 UTC, shouwn approved these changes

2019-04-21 06:26 UTC, 1eehyeji approved these changes

2019-04-21 07:49 UTC, KimJye approved these changes

2019-04-23 03:37 UTC, merged