나의 내역 조회 삭제 구현
711skhu/mobile pull request #14
Opened 2019-06-10 10:52 UTC by kje6445

2019-06-10 13:47 UTC, 1eehyeji approved these changes

2019-06-10 23:42 UTC, yjll1019 approved these changes

2019-06-11 00:34 UTC, shouwn requested changes

2019-06-11 00:34 UTC, shouwn commented on src/main/java/com/shouwn/oj/controller/user/UserController.java
> +	@GetMapping("rentalCancel/{idx}")
기존에 있던 신청을 취소(삭제) 하는 것이기 때문에 메소드를 DELETE 로 하고 cancel을 url에서 빼는 게 좋겠습니다.

url에는 행위가 들어가면 안 됩니다.

2019-06-11 00:34 UTC, shouwn commented on src/main/java/com/shouwn/oj/service/user/UserRentalListService.java
> +		HtmlTable rentalListTable2 = (HtmlTable) rentalPage.getElementById("gv대여내역");
왜 파라미터 명이 Table2인가요?

2019-06-11 00:34 UTC, shouwn commented on src/main/java/com/shouwn/oj/service/user/UserRentalListService.java
> +			for (HtmlAnchor anchor2 : rentalPage.getAnchors()) {
여기도 anchor2인 이유가 있나요?

2019-07-20 12:20 UTC, kje6445 commented on src/main/java/com/shouwn/oj/controller/user/UserController.java
> +	@GetMapping("rentalCancel/{idx}")
넹 그렇게 수정하겠습니다.

2019-07-20 17:34 UTC, kje6445 commented on src/main/java/com/shouwn/oj/service/user/UserRentalListService.java
> +		HtmlTable rentalListTable2 = (HtmlTable) rentalPage.getElementById("gv대여내역");
수정했습니당.

2019-07-20 17:34 UTC, kje6445 commented on src/main/java/com/shouwn/oj/service/user/UserRentalListService.java
> +			for (HtmlAnchor anchor2 : rentalPage.getAnchors()) {
수정했습니당.

2019-07-20 17:40 UTC, kje6445 commented
codeupdate 하고 다시 pullrequest하겠습니당

2019-07-21 02:30 UTC, shouwn commented on src/main/java/com/shouwn/oj/controller/user/UserController.java
> +	@GetMapping("delete/{idx}")
메소드를 DELETE로 하라고 말씀 드린 건 url에 delete가 있는 게 아니라

DeleteMapping을 사용해서 요청을 보낼 떄 GET 요청이 아니라 DELETE 요청을 받도록 만들라는 것이었어요.

2019-07-21 07:20 UTC, kje6445 commented on src/main/java/com/shouwn/oj/controller/user/UserController.java
> +	@GetMapping("delete/{idx}")
아항~ DelteMapping으로 다시 처리했습니다

2019-07-21 07:26 UTC, shouwn approved these changes

2019-07-21 10:31 UTC, songz1 approved these changes

2019-07-21 11:49 UTC, merged