시설물 대여 페이지 연결 코드 구현
711skhu/mobile pull request #5
Opened 2019-05-20 06:05 UTC by songz1

2019-05-20 07:17 UTC, KimJye approved these changes

2019-05-20 07:40 UTC, yjll1019 approved these changes

2019-05-20 10:45 UTC, shouwn requested changes

2019-05-20 10:45 UTC, shouwn commented on src/main/java/com/shouwn/oj/controller/rent/RentController.java
> +						.build();
이렇게 response 코드로 응답을 제어하면 컨트롤러에서 호출하는 메소드의 상태가 추가될 때마다 추가해줘야하기 때문에 상태코드보다는 예외를 보내는 게 좋을 것 같아요.

예외를 try catch 하는 형식으로 만들고 나중에 시간이 되면 다 같이 예외 컨트롤러를 만들어보죠

2019-05-20 10:45 UTC, shouwn commented on src/main/java/com/shouwn/oj/service/rent/ConnectToRentPageService.java
> +	}
위의 메소드들은 현재 클래스 내에서만 쓰이기 때문에 private 가 좋을 것 같아요.

2019-05-20 10:45 UTC, shouwn commented on src/main/java/com/shouwn/oj/controller/user/UserController.java
> +		session.setAttribute("htmlPage", null);
실제 세션을 사용하고 세션에 저장된 attribute의 name이 저장되는 곳이 서비스이기 때문에 이 코드는 서비스 쪽에 적히는 게 좋을 것 같아요.

2019-05-20 10:45 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/UrlSetting.java
> +}
단지 URL을 가져오기 위해서 무의미하게 객체를 생성하고 있기 때문에 enum으로 바꾸는 게 더 좋을 것 같습니다.

2019-05-20 11:45 UTC, 1eehyeji approved these changes

2019-05-20 15:11 UTC, songz1 commented on src/main/java/com/shouwn/oj/model/UrlSetting.java
> +}
상수형이 아닌데 enum을 사용해야 하나요? 데이터 타입을 URL로 지정해놓고 싶은데..!

2019-05-20 15:19 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/UrlSetting.java
> +}
상수형이 아니지만 해당 데이터는 모두 상태가 변하지 않고 새로 객체를 생성할 필요가 없기 때문입니다.

 enum으로도 내부적으로 URL 맴버 변수를 가지고 getter 통해 충분히 URL을 사용하실 수 있습니다.

2019-05-20 18:06 UTC, kje6445 approved these changes

2019-05-21 12:21 UTC, shouwn approved these changes

2019-05-21 12:25 UTC, merged