Feature v1.0.3 classroom rent -> 예약할 빌딩 선택 과 예약할 강의실 선택 구현
711skhu/mobile pull request #9
Opened 2019-05-25 13:54 UTC by kje6445

2019-05-25 14:13 UTC, shouwn requested changes

2019-05-25 14:13 UTC, shouwn commented on src/main/java/com/shouwn/oj/controller/rent/RentController.java
> +	}
메소드 이름이 대문자로 시작하네요.

그리고 이 코드는 프론트 코드가 아니기 때문에 click 과 같은 메소드 명은 좋지 않다고 생각합니다. GetMapping에 classRoomList, buildingList 와 비슷한 메소드 명이 좋을 것 같아요.

2019-05-25 14:13 UTC, shouwn commented on src/main/java/com/shouwn/oj/controller/rent/RentController.java
> +			System.out.println("classRoomList");
테스트를 위해 적으신 것 같은데 테스트 후에는 빼는 게 좋겠습니다.

2019-05-25 14:13 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/enums/rent/DetailType.java
> +	DetailType(String detail){this.detail=detail;}
컨벤션이 지켜져있지 않네요. PR을 하기 전에는 ctrl + alt + o 와 ctrl + alt + l(L) 을 부탁드립니다.

2019-05-25 14:13 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/enums/rent/ClassroomType.java
> +	MieleHall_M407("M407","gv시설목록_ctl13_btnSelect", DetailType.PROJECTOR, DetailType.MIDDLE);
enum의 이름을 적을 때에는 모두 대문자로 적어주세요.

2019-05-25 14:13 UTC, shouwn commented on src/main/java/com/shouwn/oj/controller/rent/RentController.java
> +	public ApiResponse<?> BuildingClick(@RequestBody BuildingRequest buildingName, HttpSession session) {
RequestBody에 들어있는 내용을 보니 String 하나 뿐인데 굳이 RequestBody를 쓸 필요가 있나 생각하게 됩니다. PathVariable은 어떤가요?

2019-05-25 14:13 UTC, shouwn commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +		}
컨트롤러와 마찬가지로 System.out.println 은 테스트가 끝나면 삭제해주세요.
로그로 남길 필요가 있는 정보가 있다면 Slfj 를 사용해주세요.

2019-05-25 14:13 UTC, shouwn commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +			String str = anchor.getId();
이 변수는 새로운 값을 배정만 받고 사용하는 코드가 없는데 왜 만든 것인가요?

2019-05-25 14:13 UTC, shouwn commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +				}
코딩 컨벤션이 맞춰져있지 않네요.

2019-05-25 14:13 UTC, shouwn commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +				}
enum을 사용할 경우 switch 문을 사용할 수 있으니 한번 염두해보시는 것도 좋을 것 같습니다.

2019-05-25 14:13 UTC, shouwn commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +			 link.click();
if 문 안에서 행하는 str에 새로운 값을 배정하는 것과 link = anchor 가 의미가 있나 생각이 드네요.

정해진 빌딩 이름 외에 것을 클릭하는 걸 맞기 위해서라고 해도 그 경우 link는 반복문 이전의 값이거나 null일 것이기 때문에 버그가 있을 것 같습니다.

어떠한 이유로 이러한 if문이 생긴 것인가요?

2019-05-25 14:13 UTC, shouwn commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +		link.click();
clickBuilding과 같은 내용의 이슈입니다.

2019-05-25 14:13 UTC, shouwn commented on src/main/java/com/shouwn/oj/service/user/UserService.java
>  			loginForm.getInputByName("txtPW").setValueAttribute(loginRequest.getPassword());
테스트 용도의 System.out.println은 PR할 때는 빼주세요.

2019-05-26 07:03 UTC, songz1 requested changes

2019-05-26 07:03 UTC, songz1 commented on src/main/java/com/shouwn/oj/model/enums/rent/ClassroomType.java
> +	MieleHall_M402("M402","gv시설목록_ctl09_btnSelect", DetailType.PROJECTOR, DetailType.MIDDLE),
M402는 컴퓨터와 빔프로젝터 둘 다 특이사항에 포함될텐데, 빔프로젝터만 포함되어 있네요.

2019-05-26 07:03 UTC, songz1 commented on src/main/java/com/shouwn/oj/controller/rent/RentController.java
> +	public ApiResponse<?> ClassRoomClick(@RequestBody ClassRoomRequest classRoomName, HttpSession session) {
강의실 목록 조회 컨트롤러는 어디에 있나요?

2019-05-26 07:03 UTC, songz1 commented on src/main/java/com/shouwn/oj/controller/rent/RentController.java
> +	}
(메소드명과 URI 모두) 건물/강의실을 선택하는 기능이니까 selectBuilding 같은 이름이 구분하기에 더 수월할 것 같습니다.

2019-05-26 07:03 UTC, songz1 commented on src/main/java/com/shouwn/oj/controller/rent/RentController.java
> +	public ApiResponse<?> BuildingClick(@RequestBody BuildingRequest buildingName, HttpSession session) {
PathVariable 좋은 것 같아요. 
근데 PathVariable을 사용하면 GetMapping일텐데, 단순 조회가 아닌 작업을 수행하는 메소드는 PostMapping이 더 적합하지 않나요? 이런 경우엔 어떤 방식이 나을까요?

2019-05-26 07:03 UTC, songz1 commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +		buildingList2 = rentPage.getByXPath("//table[@id='gv건물목록']/tbody/tr[@class='cssAlternatingRowStyle']/td[1]");
XPath로 받으면 클래스명이 다른 행들 때문에 각각 따로 리스트를 만들어서 찾아줘야 하니까,
그냥 'gv건물목록' 테이블을 받아서 getRow/getCell 하는 방식은 어떤가요?
지금 나뉘는 클래스명도 css 스타일로 나뉘는거라 나중에 forest에서 css 스타일이 변경되면 코드를 수정하는 일이 생길 것 같아요.

2019-05-26 07:03 UTC, songz1 commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +			clickBuilding(rentPage, buildingName);
clickBuilding 메소드를 왜 따로 만드신건가요? 
현재 selectBuilding에서 건물 목록을 출력하는 과정은 불필요한 작업입니다.  

clickBuilding만 사용하거나, selectBuilding의 내용을 수정해주세요.

2019-05-26 07:03 UTC, songz1 commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +		link.click();
컨트롤러 뿐만 아니라 서비스도 강의실 목록을 조회하는 클래스가 없네요. 
API 추가 부탁드려요!

2019-05-26 07:07 UTC, shouwn commented on src/main/java/com/shouwn/oj/controller/rent/RentController.java
> +	public ApiResponse<?> BuildingClick(@RequestBody BuildingRequest buildingName, HttpSession session) {
작업 수행은 외부에는 알려지지 않고 서버 내부에서만 행해지게 됩니다. 서버 API를 쓰는 외부 프로그램은 단순히 데이터를 가져오는 행위만 하는 것이기 때문에 GET이 좋을 것 같다고 생각해요.

2019-05-26 07:11 UTC, shouwn commented on src/main/java/com/shouwn/oj/controller/rent/RentController.java
> +	}
select는 프론트에서 쓸 것 같은 메소드 네이밍이라서 저는 Http 메소드 명과 자바 getter와 같이 get이 더 좋을 것 같아요.

2019-05-26 07:15 UTC, songz1 commented on src/main/java/com/shouwn/oj/controller/rent/RentController.java
> +	public ApiResponse<?> BuildingClick(@RequestBody BuildingRequest buildingName, HttpSession session) {
아하 그렇군요

2019-05-27 02:49 UTC, kje6445 commented on src/main/java/com/shouwn/oj/model/enums/rent/ClassroomType.java
> +	MieleHall_M402("M402","gv시설목록_ctl09_btnSelect", DetailType.PROJECTOR, DetailType.MIDDLE),
M402만 예외상황으로 2개가 포함되었기 때문에 M402가 호출될때 따로 DetailType.COMPUTER을 넣는 방향으로 하겠습니다.

2019-05-27 02:54 UTC, kje6445 commented on src/main/java/com/shouwn/oj/controller/rent/RentController.java
> +	public ApiResponse<?> ClassRoomClick(@RequestBody ClassRoomRequest classRoomName, HttpSession session) {
강의실 목록 조회는 불필요합니다.  건물 이름 받아 건물 선택이 되면 자동적으로 페이지 내에서 보여주고 그 안에서 강의실 번호를 입력 받으면 버튼이 클릭되는 방식으로 구동하게됩니다.

2019-05-27 02:59 UTC, songz1 commented on src/main/java/com/shouwn/oj/controller/rent/RentController.java
> +	public ApiResponse<?> ClassRoomClick(@RequestBody ClassRoomRequest classRoomName, HttpSession session) {
그 방식으로 하려면 프론트쪽이랑 얘기가 먼저 되어야할 것 같아요. 지금은 프론트쪽이 서버 요청 없이 보여주기로 한 정보는 건물 목록뿐이고, 강의실 목록은 저희가 넘겨줘야 하는게 맞아요.

2019-05-27 03:40 UTC, shouwn commented on src/main/java/com/shouwn/oj/model/enums/rent/ClassroomType.java
> +	MieleHall_M402("M402","gv시설목록_ctl09_btnSelect", DetailType.PROJECTOR, DetailType.MIDDLE),
detail에 여러가지가 추가될 수 있으니 배열을 사용하는 방법은 어떤가요?

2019-05-27 06:38 UTC, kje6445 commented on src/main/java/com/shouwn/oj/model/enums/rent/ClassroomType.java
> +	MieleHall_M402("M402","gv시설목록_ctl09_btnSelect", DetailType.PROJECTOR, DetailType.MIDDLE),
detail부분을 배열로서 받으라는 말씀이신가요?

2019-05-27 06:43 UTC, kje6445 commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +			clickBuilding(rentPage, buildingName);
이름을 입력 받고 그것에 따른 버튼 이름에 맞게 적용하는 절차가 있어 clickBuillding메소드를 따로 구현하였습니다.

2019-05-27 06:46 UTC, kje6445 commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +		buildingList2 = rentPage.getByXPath("//table[@id='gv건물목록']/tbody/tr[@class='cssAlternatingRowStyle']/td[1]");
일단 건물 목록을 받는 것은 불필요한 작업으로 강의실 목록에 사용하겠습니다.

2019-05-28 03:40 UTC, kje6445 commented on src/main/java/com/shouwn/oj/model/enums/rent/ClassroomType.java
> +	MieleHall_M402("M402","gv시설목록_ctl09_btnSelect", DetailType.PROJECTOR, DetailType.MIDDLE),
수정완료

2019-05-28 04:35 UTC, shouwn commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +				}
불필요한 if문 삭제

2019-05-28 04:35 UTC, shouwn commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +			 link.click();
불필요한 if문 삭제

2019-05-29 08:43 UTC, songz1 approved these changes

2019-05-29 11:42 UTC, 1eehyeji approved these changes

2019-05-29 13:38 UTC, shouwn commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +							Thread.sleep(3000);
왜 3초간 슬립하는 건가요?

2019-05-29 14:33 UTC, songz1 commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +							Thread.sleep(3000);
실행하는데에 시간이 좀 걸려서요! sleep 해주지 않으면 실행 완료 전에 다음 코드로 넘어가서 제대로 읽어오질 못하더라구요.

2019-05-29 14:36 UTC, shouwn commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +							Thread.sleep(3000);
그러면 심각한 문제가 될 수 있습니다. 현재는 3초 후에 작업이 완료되지만 3초가 넘게 걸릴 수도 있습니다. 그러면 프로그램 버그로 이어지기 때문에 고쳐야 합니다.

click 이벤트 후에 HtmlUnit 작업이 끝났는지 확인할 수 있는 메소드는 없나요?

2019-05-29 14:48 UTC, shouwn commented on src/main/java/com/shouwn/oj/service/rent/LectureRoomService.java
> +							Thread.sleep(3000);
의논 결과 추후 과제로 남았습니다.

2019-05-29 14:48 UTC, shouwn approved these changes

2019-05-30 03:03 UTC, merged